/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package arayuzu;

import ayarlar.ButtonAyarlari;
import ayarlar.TextAyarlari;
import java.awt.Color;

/**
 *
 * @author chame
 */
public class OdemeEkrani extends javax.swing.JFrame {

    /** Creates new form OdemeEkrani */
    private final String kartUzerindekiIsim= "" ;
    private final String kartNo= "" ;
    private final String kartCVV= "" ;
    public OdemeEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
        odemeEkranPanel.setFocusable(true);
        TextAyarlari.isimKontrol(kartUzerindrkiIsmiGirTextField);
        TextAyarlari.kartNoKontrol(kartNoGirTextField);
        TextAyarlari.cvvKontrol(CVVGirPasswordField);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        odemeEkranPanel = new javax.swing.JPanel();
        mesajLabel = new javax.swing.JLabel();
        kartUzerindekiIsimLabel = new javax.swing.JLabel();
        kartNoLabel = new javax.swing.JLabel();
        CVVLabel = new javax.swing.JLabel();
        sonKullanimTarihiLabel = new javax.swing.JLabel();
        sonKullanimAyComboBox = new javax.swing.JComboBox<>();
        sonKullanimYiliComboBox = new javax.swing.JComboBox<>();
        odemeButton = new javax.swing.JButton();
        kartUzerindrkiIsmiGirTextField = new javax.swing.JTextField();
        kartNoGirTextField = new javax.swing.JTextField();
        CVVGirPasswordField = new javax.swing.JPasswordField();
        slasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        odemeEkranPanel.setBackground(new java.awt.Color(255, 204, 204));

        mesajLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mesajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesajLabel.setText("Ucak Bilet Reservasiyon Sistemi");

        kartUzerindekiIsimLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kartUzerindekiIsimLabel.setText("Kart Uzerindeki isim  :");

        kartNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kartNoLabel.setText("Kart Numarasi  :");

        CVVLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CVVLabel.setText("Guvenlik kodu :");

        sonKullanimTarihiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sonKullanimTarihiLabel.setText("Son kullanim tarihi :");

        sonKullanimAyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ay", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        sonKullanimYiliComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yil", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037" }));

        odemeButton.setBackground(new java.awt.Color(102, 153, 255));
        odemeButton.setText("Odeme Yap");
        odemeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                odemeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                odemeButtonMouseExited(evt);
            }
        });

        kartNoGirTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartNoGirTextFieldActionPerformed(evt);
            }
        });

        slasLabel.setText("/");

        javax.swing.GroupLayout odemeEkranPanelLayout = new javax.swing.GroupLayout(odemeEkranPanel);
        odemeEkranPanel.setLayout(odemeEkranPanelLayout);
        odemeEkranPanelLayout.setHorizontalGroup(
            odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, odemeEkranPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                        .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sonKullanimTarihiLabel)
                                    .addComponent(CVVLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CVVGirPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                                        .addComponent(sonKullanimAyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slasLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sonKullanimYiliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                                    .addComponent(kartNoLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kartNoGirTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, odemeEkranPanelLayout.createSequentialGroup()
                                    .addComponent(kartUzerindekiIsimLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kartUzerindrkiIsmiGirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(mesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, odemeEkranPanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(odemeButton)))
                .addGap(36, 36, 36))
        );

        odemeEkranPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CVVLabel, kartNoLabel, kartUzerindekiIsimLabel, sonKullanimTarihiLabel});

        odemeEkranPanelLayout.setVerticalGroup(
            odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odemeEkranPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kartUzerindrkiIsmiGirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kartUzerindekiIsimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kartNoGirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kartNoLabel))
                .addGap(18, 18, 18)
                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CVVGirPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CVVLabel))
                .addGap(18, 18, 18)
                .addGroup(odemeEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonKullanimTarihiLabel)
                    .addComponent(sonKullanimAyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonKullanimYiliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slasLabel))
                .addGap(18, 18, 18)
                .addComponent(odemeButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        odemeEkranPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CVVGirPasswordField, CVVLabel, kartNoGirTextField, kartNoLabel, kartUzerindekiIsimLabel, kartUzerindrkiIsmiGirTextField, odemeButton, sonKullanimAyComboBox, sonKullanimTarihiLabel, sonKullanimYiliComboBox});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(odemeEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(odemeEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kartNoGirTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartNoGirTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kartNoGirTextFieldActionPerformed

    private void odemeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemeButtonMouseEntered
        ButtonAyarlari.setBackgRenk(odemeButton, Color.pink);
    }//GEN-LAST:event_odemeButtonMouseEntered

    private void odemeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemeButtonMouseExited
        ButtonAyarlari.setOrijRenk(odemeButton);
    }//GEN-LAST:event_odemeButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdemeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CVVGirPasswordField;
    private javax.swing.JLabel CVVLabel;
    private javax.swing.JTextField kartNoGirTextField;
    private javax.swing.JLabel kartNoLabel;
    private javax.swing.JLabel kartUzerindekiIsimLabel;
    private javax.swing.JTextField kartUzerindrkiIsmiGirTextField;
    private javax.swing.JLabel mesajLabel;
    private javax.swing.JButton odemeButton;
    private javax.swing.JPanel odemeEkranPanel;
    private javax.swing.JLabel slasLabel;
    private javax.swing.JComboBox<String> sonKullanimAyComboBox;
    private javax.swing.JLabel sonKullanimTarihiLabel;
    private javax.swing.JComboBox<String> sonKullanimYiliComboBox;
    // End of variables declaration//GEN-END:variables

}
