/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ButtonAyarlari;
import java.awt.Color;

/**
 *
 * @author chame
 */
public class SeferSecEkrani extends javax.swing.JFrame {

    /**
     * Creates new form SeferSecEkrani
     */
    public SeferSecEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seferSecEkranPanel = new javax.swing.JPanel();
        mesajLabel = new javax.swing.JLabel();
        neredenComboBox = new javax.swing.JComboBox<>();
        nereyeComboBox = new javax.swing.JComboBox<>();
        biletBulButton = new javax.swing.JButton();
        yolcuSayisiComboBox = new javax.swing.JComboBox<>();
        tekYonRadioButton = new javax.swing.JRadioButton();
        aktarmasizRadioButton = new javax.swing.JRadioButton();
        donusTarihiGirTextField = new javax.swing.JTextField();
        gidisTarihiGirTextField = new javax.swing.JTextField();
        gidisTarihiLabel = new javax.swing.JLabel();
        donusTarihiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        seferSecEkranPanel.setBackground(new java.awt.Color(255, 51, 255));

        mesajLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mesajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesajLabel.setText("Ucuz Ucak Bileti Reservasiyon Sistemi");

        neredenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEREDEN", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));

        nereyeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEREYE", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));

        biletBulButton.setText("Bilet Bul");
        biletBulButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                biletBulButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                biletBulButtonMouseExited(evt);
            }
        });

        yolcuSayisiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yolcu sayısı", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        tekYonRadioButton.setText("Tek Yon");

        aktarmasizRadioButton.setText("aktarmasiz");

        donusTarihiGirTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donusTarihiGirTextFieldActionPerformed(evt);
            }
        });

        gidisTarihiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gidisTarihiLabel.setText("Gidis Tarihi :");

        donusTarihiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donusTarihiLabel.setText("Donus Tarihi :");

        javax.swing.GroupLayout seferSecEkranPanelLayout = new javax.swing.GroupLayout(seferSecEkranPanel);
        seferSecEkranPanel.setLayout(seferSecEkranPanelLayout);
        seferSecEkranPanelLayout.setHorizontalGroup(
            seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seferSecEkranPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(yolcuSayisiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gidisTarihiLabel)
                            .addComponent(neredenComboBox, 0, 101, Short.MAX_VALUE)))
                    .addComponent(donusTarihiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nereyeComboBox, 0, 95, Short.MAX_VALUE)
                    .addComponent(tekYonRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aktarmasizRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gidisTarihiGirTextField)
                    .addComponent(donusTarihiGirTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(seferSecEkranPanelLayout.createSequentialGroup()
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seferSecEkranPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(biletBulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seferSecEkranPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(mesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        seferSecEkranPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {donusTarihiLabel, gidisTarihiLabel, neredenComboBox, nereyeComboBox, yolcuSayisiComboBox});

        seferSecEkranPanelLayout.setVerticalGroup(
            seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seferSecEkranPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(mesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neredenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nereyeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gidisTarihiLabel)
                    .addComponent(gidisTarihiGirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donusTarihiGirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donusTarihiLabel))
                .addGap(18, 18, 18)
                .addGroup(seferSecEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tekYonRadioButton)
                    .addComponent(yolcuSayisiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aktarmasizRadioButton)
                .addGap(18, 18, 18)
                .addComponent(biletBulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        seferSecEkranPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {donusTarihiGirTextField, donusTarihiLabel, gidisTarihiGirTextField, gidisTarihiLabel, neredenComboBox, nereyeComboBox});

        seferSecEkranPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aktarmasizRadioButton, tekYonRadioButton, yolcuSayisiComboBox});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seferSecEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seferSecEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donusTarihiGirTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donusTarihiGirTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donusTarihiGirTextFieldActionPerformed
    
    private void biletBulButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biletBulButtonMouseEntered
       ButtonAyarlari.setBackgRenk(biletBulButton, Color.PINK);
    }//GEN-LAST:event_biletBulButtonMouseEntered

    private void biletBulButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biletBulButtonMouseExited
        ButtonAyarlari.setOrijRenk(biletBulButton);
    }//GEN-LAST:event_biletBulButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeferSecEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeferSecEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeferSecEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeferSecEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeferSecEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aktarmasizRadioButton;
    private javax.swing.JButton biletBulButton;
    private javax.swing.JTextField donusTarihiGirTextField;
    private javax.swing.JLabel donusTarihiLabel;
    private javax.swing.JTextField gidisTarihiGirTextField;
    private javax.swing.JLabel gidisTarihiLabel;
    private javax.swing.JLabel mesajLabel;
    private javax.swing.JComboBox<String> neredenComboBox;
    private javax.swing.JComboBox<String> nereyeComboBox;
    private javax.swing.JPanel seferSecEkranPanel;
    private javax.swing.JRadioButton tekYonRadioButton;
    private javax.swing.JComboBox<String> yolcuSayisiComboBox;
    // End of variables declaration//GEN-END:variables
}
